Repository 10up/eight-day-week, pull requests merged in 2019-07, with the labels that each got.

#30 Add plugin images for .ORG
  .gitignore
  .wordpress-org/banner-1544x500-rtl.png
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250-rtl.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
Labels: documentation

#31 Add German translation files
  languages/eight-day-week-de_DE.mo
  languages/eight-day-week-de_DE.po
Labels: enhancement

#32 Fix DateTimeZone setup: fall back to gmt_offset; php notice fixes
  includes/functions/plugins/article-export.php
Labels: bug
